spring:
  profiles:
    active: h2

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - logfile

  endpoint:
    health:
      show-details: when_authorized
      roles: ROLE_ADMIN

server:
  port: 8081

logging:
  file: library.log
  level:
    org.springframework.web: info
    org.hibernate: error


---
spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:library
    initialization-mode: always
    schema: classpath:/schema/schema.sql
    data: classpath:/schema/data.sql
  jpa:
    hibernate:
       ddl-auto: update
  h2:
     console:
        enabled: true

---

spring:
  profiles: postgres
  datasource:
    username: postgres
    password: 784512963
    url: jdbc:postgresql://localhost:5432/library
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    schema: classpath:/schema/schema.sql
    data: classpath:/schema/data.sql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  profiles: emptyH2
  datasource:
      url: jdbc:h2:mem:library
      initialization-mode: always
      schema: classpath:/schema/schema.sql
  jpa:
      hibernate:
         ddl-auto: update